packages:
  - docs
  - examples/*
  - packages/*
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  workerd: false
linkWorkspacePackages: true
preferWorkspacePackages: true
# This prevents the examples to have the `workspace:` prefix
saveWorkspaceProtocol: false
overrides:
  'vite-plugin-astro>@astrojs/internal-helpers': 'file:../../withastro/astro/packages/internal-helpers'
